name: Jail
main: net.simpvp.Jail.Jail
version: 4
api-version: 1.13
author: simpvp.net
description: A minimalist jail plugin.
softdepend: [Multiverse-Core]
commands:
  jail:
    description: Jail a player.
  unjail:
    description: Unjail a player.
  jailinfo:
    description: Show info about jail in general or a particular jailed player.
  jailreload:
    description: Reload the jail config.
